module.exports = {
  cliente: {
    nome: "SKN Prime",
    subdomain: "sknprime-bi",
    coolify_app_uuid: "gx6mqzy4m08gp9rfxpq60sp1",
    cor_primaria: "#22d3ee",
  },
  fontes: {
    adapters: ["nibo-xlsx"],
    nibo_xlsx: {
      base_file: "Base Nibo.xlsx",
      conta_filter: [],
    },
    drive: {
      base_path: "G:/Meu Drive/BGP/CLIENTES/BI/462. SKN PRIME/BASES",
    },
  },
  pages: {
    geral: {
      capa: "active",
      overview: "active",
      receita: "active",
      despesa: "active",
      fluxo: "active",
      tesouraria: "active",
      comparativo: "active",
      relatorio: "active",
      valuation: "hidden",
    },
    outros: {
      orcamento: "hidden",
      lojas: "hidden",
      risco: "hidden",
      indicators: "hidden",
      faturamento_produto: "hidden",
      curva_abc: "hidden",
      marketing: "hidden",
      hierarquia: "hidden",
      comercial: "active",
      detalhado: "hidden",
      profunda_cliente: "hidden",
      crm: "hidden",
      organograma: "active",
      folha_pgto: "active",
      custo_depto: "active",
      inadimplencia: "active",
      qtd_clientes: "active",
      receita_nova: "active",
      margem_contrib: "active",
    },
  },
  meta: {
    ano_corrente: 2026,
    metas_crm: { mes: 0, ano: 0 },
    valuation_premissas: { wacc: 25, growth_year2: 20, growth_year3: 20, ipca: 4.5, perpetuity_growth: 10 },
  },
  template: { version_when_created: "1.0.0", version_last_synced: "1.0.0" },
};
